package co.com.hyunseda.market.presentation;

import co.com.hyunseda.market.domain.Category;
import co.com.hyunseda.market.domain.Product;
import co.com.hyunseda.market.service.CategoryService;
import co.com.hyunseda.market.service.ProductService;
import java.util.List;

/**
 *
 * @author JUAN DAVID
 */
public class GUICategoryNew extends javax.swing.JFrame {

       ProductService productService;
       CategoryService categoryService;
       private boolean addOption;

    public void setAddOption(boolean addOption) {
        this.addOption = addOption;
    }
    /**
     * Creates new form GUICategoryFind
     */
    /*public GUICategoryNew(ProductService productService) {
        initComponents();
        this.productService = productService;
        stateInitial();
    }*/
    public GUICategoryNew(CategoryService categoryService) {
        initComponents();
        this.categoryService = categoryService;
        stateInitial();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSouth = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblNewCategoryTittle = new javax.swing.JLabel();
        pnlCenterOptions = new javax.swing.JPanel();
        lblNewCategoryId = new javax.swing.JLabel();
        txtIdNewCategory = new javax.swing.JTextField();
        lblNewCategoryName = new javax.swing.JLabel();
        txtNameNewCategory = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1040, 720));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setText("Regresar");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlSouth.add(btnBack);

        btnGrabar.setBackground(new java.awt.Color(153, 255, 153));
        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        pnlSouth.add(btnGrabar);

        btnClose.setBackground(new java.awt.Color(255, 102, 102));
        btnClose.setText("Cerrar");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlSouth.add(btnClose);

        getContentPane().add(pnlSouth, java.awt.BorderLayout.PAGE_END);

        lblNewCategoryTittle.setFont(new java.awt.Font("Perpetua", 3, 18)); // NOI18N
        lblNewCategoryTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNewCategoryTittle.setText("AGREGAR CATEGORÍA");
        getContentPane().add(lblNewCategoryTittle, java.awt.BorderLayout.PAGE_START);

        pnlCenterOptions.setLayout(new java.awt.GridLayout(2, 2));

        lblNewCategoryId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNewCategoryId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNewCategoryId.setText("*Id");
        pnlCenterOptions.add(lblNewCategoryId);

        txtIdNewCategory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlCenterOptions.add(txtIdNewCategory);

        lblNewCategoryName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNewCategoryName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNewCategoryName.setText("*Nombre");
        pnlCenterOptions.add(lblNewCategoryName);

        txtNameNewCategory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnlCenterOptions.add(txtNameNewCategory);

        getContentPane().add(pnlCenterOptions, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
         if (txtNameNewCategory.getText().trim().equals("")) {
            Messages.showMessageDialog("Debe ingresar el nombre de la categoria", "Atención");
            txtNameNewCategory.requestFocus();
            return;
        } 
        if(txtIdNewCategory.getText().trim().equals("")){
            Messages.showMessageDialog("Debe ingresar el id de la categoria", "Atención");
            txtIdNewCategory.requestFocus();
            return;
        }
            addCategory();
            System.out.println("SE GRABÓ");


    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        /*GUIMainMenu menuPrincipal = new GUIMainMenu(productService,categoryService);*/
        GUIMainMenu menuPrincipal = new GUIMainMenu();
        menuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed
    private void stateInitial() {

            btnClose.setVisible(true);
            btnBack.setVisible(true);
            btnGrabar.setVisible(true);
            txtIdNewCategory.setEnabled(true);
            txtNameNewCategory.setEnabled(true);

        }
    /**
     pnlSouthm args thebtonCerrar line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICategoryNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICategoryNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICategoryNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICategoryNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JLabel lblNewCategoryId;
    private javax.swing.JLabel lblNewCategoryName;
    private javax.swing.JLabel lblNewCategoryTittle;
    private javax.swing.JPanel pnlCenterOptions;
    private javax.swing.JPanel pnlSouth;
    private javax.swing.JTextField txtIdNewCategory;
    private javax.swing.JTextField txtNameNewCategory;
    // End of variables declaration//GEN-END:variables
    
    private void cleanControls() {
        txtNameNewCategory.setText("");
        txtIdNewCategory.setText("");
    }
    
    private void addCategory() {
        try{
            
            String name = txtNameNewCategory.getText().trim();
            String id = txtIdNewCategory.getText().trim();
            int idCategory = Integer.parseInt(id);
            
            //Realizar una solicitud al backend para obtener una lista actualizada de categorias
            List<Category> categories = categoryService.findAllCategories();
            
            Category newCategory = new Category(idCategory, name);
            
            //Verificar si el ID ingresado ya esta en uso
            boolean idExists = categories.stream().anyMatch(category -> category.getCategoryId() == idCategory);
            if(idExists){
                Messages.showMessageDialog("El id de la categoria ya esta en uso", "ERROR DE ENTRADA");
                return;
            }
            
            if (categoryService.saveCategory(newCategory)) {
                Messages.showMessageDialog("Se grabó con éxito", "Atención");
                cleanControls();
                stateInitial();
            } else {
                Messages.showMessageDialog("Error al grabar, lo siento mucho", "Atención");
            }
        }catch(NumberFormatException ex){
            Messages.showMessageDialog("El ID de la categoría debe ser un número válido", "Error de Entrada");
        }
    }

}
